import jsPDF from "jspdf";
import { parseSummary } from "./parse-summary";

export function generateSummaryPDF(title: string, createdAt: string, fileName: string, summaryText: string) {
  const doc = new jsPDF({
    orientation: "portrait",
    unit: "mm",
    format: "a4",
  });

  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 20;
  const maxLineWidth = pageWidth - margin * 2;
  
  let cursorY = margin;

  const addText = (text: string, fontSize: number, isBold: boolean, color: number[], autoWrap: boolean = true) => {
    // Strip emojis for jsPDF which can't render them well with standard fonts
    const safeText = text.replace(/([\u2700-\u27BF]|[\uE000-\uF8FF]|\uD83C[\uDC00-\uDFFF]|\uD83D[\uDC00-\uDFFF]|[\u2011-\u26FF]|\uD83E[\uDD10-\uDDFF])/g, '');
    
    doc.setFont("helvetica", isBold ? "bold" : "normal");
    doc.setFontSize(fontSize);
    doc.setTextColor(color[0], color[1], color[2]);

    const lines = autoWrap ? doc.splitTextToSize(safeText, maxLineWidth) : [safeText];
    
    lines.forEach((line: string) => {
      if (cursorY + 10 > pageHeight - margin) {
        doc.addPage();
        cursorY = margin;
      }
      doc.text(line, margin, cursorY);
      cursorY += (fontSize * 0.4); 
    });
    cursorY += 4; 
  };

  // --- Title & Metadata ---
  addText(title, 22, true, [15, 23, 42]);
  cursorY += 4;
  
  const dateStr = new Date(createdAt).toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" });
  addText(`Source File: ${fileName}`, 10, false, [100, 116, 139]);
  cursorY -= 2;
  addText(`Generated on: ${dateStr}`, 10, false, [100, 116, 139]);
  cursorY += 6;
  
  // Line separator
  doc.setDrawColor(226, 232, 240);
  doc.line(margin, cursorY, pageWidth - margin, cursorY);
  cursorY += 12;

  // --- Content ---
  const sections = parseSummary(summaryText);

  sections.forEach((section) => {
    if (section.title) {
      addText(section.title, 14, true, [15, 23, 42]);
      cursorY += 2;
    }

    section.points.forEach((point) => {
      // Strip emojis
      const safePoint = point.replace(/([\u2700-\u27BF]|[\uE000-\uF8FF]|\uD83C[\uDC00-\uDFFF]|\uD83D[\uDC00-\uDFFF]|[\u2011-\u26FF]|\uD83E[\uDD10-\uDDFF])/g, '');
      
      doc.setFont("helvetica", "normal");
      doc.setFontSize(11);
      doc.setTextColor(51, 65, 85);
      
      const bulletLines = doc.splitTextToSize(safePoint, maxLineWidth - 6);
      bulletLines.forEach((bLine: string, bIndex: number) => {
        if (cursorY + 10 > pageHeight - margin) {
          doc.addPage();
          cursorY = margin;
        }
        if (bIndex === 0) {
          doc.text("•", margin, cursorY);
          doc.text(bLine, margin + 6, cursorY);
        } else {
          doc.text(bLine, margin + 6, cursorY);
        }
        cursorY += 5.5; 
      });
      cursorY += 2;
    });
    cursorY += 6;
  });

  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
      doc.setPage(i);
      doc.setFont("helvetica", "normal");
      doc.setFontSize(9);
      doc.setTextColor(148, 163, 184);
      doc.text(`Page ${i} of ${pageCount}  —  Generated by Quicker`, pageWidth / 2, pageHeight - 12, { align: 'center' });
  }

  doc.save(`Summary-${title.replace(/[^a-z0-9]/gi, "_").slice(0, 50)}.pdf`);
}
